"use client";

import { useState } from "react";
import { BadgeDollarSign, CheckCircle2, Trash2, Plus } from "lucide-react";
import { useStore } from "@/lib/store";
import { Fee, FeeStatus, Section } from "@/lib/types";

export default function AdminFeesPage() {
  const { students, fees, addFee, updateFeeStatus, deleteFee } = useStore();
  const [form, setForm] = useState({ studentId: students[0]?.id ?? "", section: "quran" as Section, title: "Monthly Fee", amount: 0, dueDate: "", note: "" });
  const submit = (e: React.FormEvent) => { e.preventDefault(); const student = students.find((s) => s.id === form.studentId); if (!student || !student.sections.includes(form.section) || !form.title.trim() || form.amount < 0) return; addFee({ studentId: student.id, section: form.section, title: form.title.trim(), amount: Number(form.amount), dueDate: form.dueDate || null, status: "pending", note: form.note.trim() }); setForm((f) => ({ ...f, title: "Monthly Fee", amount: 0, dueDate: "", note: "" })); };
  const sorted = fees.slice().sort((a, b) => b.createdAt.localeCompare(a.createdAt));
  return <div className="space-y-8"><div><p className="text-xs font-semibold tracking-wide uppercase text-[var(--gold)]">Fees</p><h1 className="font-display text-3xl mt-1 text-[var(--heading)]">Fee Management</h1><p className="text-sm text-[var(--ink-soft)] mt-1">Add, mark paid, waive, or remove fee entries. Quran and Academy fees stay separate.</p></div>
    <form onSubmit={submit} className="rounded-2xl border border-[var(--line)] bg-[var(--surface)] p-6 space-y-4"><div className="flex items-center gap-2"><BadgeDollarSign size={18} className="text-[var(--gold)]" /><h2 className="font-display text-xl text-[var(--heading)]">Add Fee</h2></div><div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-4"><Field label="Student"><select value={form.studentId} onChange={(e) => { const student = students.find((s) => s.id === e.target.value); const section = student?.sections.includes(form.section) ? form.section : student?.sections[0] ?? "quran"; setForm({ ...form, studentId: e.target.value, section }); }} className={inputClass}>{students.map((s) => <option key={s.id} value={s.id}>{s.name}</option>)}</select></Field><Field label="Section"><select value={form.section} onChange={(e) => setForm({ ...form, section: e.target.value as Section })} className={inputClass}>{(students.find((s) => s.id === form.studentId)?.sections ?? ["quran"]).map((s) => <option key={s} value={s}>{s === "quran" ? "Quran" : "Academy"}</option>)}</select></Field><Field label="Title"><input value={form.title} onChange={(e) => setForm({ ...form, title: e.target.value })} className={inputClass} /></Field><Field label="Amount (Rs.)"><input type="number" min={0} step="0.01" value={form.amount} onChange={(e) => setForm({ ...form, amount: Number(e.target.value) })} className={inputClass} /></Field><Field label="Due date"><input type="date" value={form.dueDate} onChange={(e) => setForm({ ...form, dueDate: e.target.value })} className={inputClass} /></Field><Field label="Note"><input value={form.note} onChange={(e) => setForm({ ...form, note: e.target.value })} className={inputClass} /></Field></div><button className="inline-flex items-center gap-2 px-5 py-2.5 rounded-full bg-[var(--primary)] text-white text-sm font-medium"><Plus size={14} /> Add Fee</button></form>
    <div className="space-y-3"><h2 className="font-display text-xl text-[var(--heading)]">Fee Records</h2>{sorted.length === 0 && <p className="text-sm text-[var(--ink-faint)]">No fees added yet.</p>}{sorted.map((f) => <FeeRow key={f.id} fee={f} studentName={students.find((s) => s.id === f.studentId)?.name ?? "Removed student"} onStatus={updateFeeStatus} onDelete={() => deleteFee(f.id)} />)}</div>
  </div>;
}

function FeeRow({ fee, studentName, onStatus, onDelete }: { fee: Fee; studentName: string; onStatus: (id: string, status: FeeStatus) => void; onDelete: () => void }) { return <div className="rounded-xl border border-[var(--line)] bg-[var(--surface)] p-4"><div className="flex items-start justify-between gap-4 flex-wrap"><div><p className="font-medium text-[var(--ink)]">{studentName} · {fee.title}</p><p className="text-xs text-[var(--ink-faint)] mt-1">{fee.section === "quran" ? "Quran" : "Academy"}{fee.dueDate ? ` · Due ${fee.dueDate}` : ""}{fee.note ? ` · ${fee.note}` : ""}</p></div><p className="font-semibold text-[var(--heading)]">Rs. {fee.amount}</p></div><div className="mt-3 flex flex-wrap gap-2"><button onClick={() => onStatus(fee.id, "paid")} className={`inline-flex items-center gap-1.5 px-3 py-1.5 rounded-full text-xs ${fee.status === "paid" ? "bg-[var(--primary-tint)] text-[var(--heading)]" : "border border-[var(--line)] text-[var(--ink-soft)]"}`}><CheckCircle2 size={12} /> Paid</button><button onClick={() => onStatus(fee.id, "pending")} className={`px-3 py-1.5 rounded-full text-xs ${fee.status === "pending" ? "bg-[var(--gold-soft)] text-[var(--gold)]" : "border border-[var(--line)] text-[var(--ink-soft)]"}`}>Pending</button><button onClick={() => onStatus(fee.id, "waived")} className={`px-3 py-1.5 rounded-full text-xs ${fee.status === "waived" ? "bg-[var(--gold-soft)] text-[var(--gold)]" : "border border-[var(--line)] text-[var(--ink-soft)]"}`}>Waived</button><button onClick={onDelete} className="ml-auto inline-flex items-center gap-1.5 px-3 py-1.5 rounded-full text-xs text-[var(--rose)] hover:bg-[var(--rose-tint)]"><Trash2 size={12} /> Delete</button></div></div>; }

const inputClass = "mt-1.5 w-full rounded-xl border border-[var(--line)] bg-[var(--bg)] px-4 py-2.5 text-sm outline-none focus:border-[var(--primary)]";
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <div><label className="text-xs font-medium text-[var(--ink-faint)]">{label}</label>{children}</div>; }
