/**
 * IDs generated by the client must be valid UUIDs because the Supabase tables
 * use uuid primary keys. `crypto.randomUUID()` is available in modern browsers
 * (including Vercel deployments). The fallback is only for older environments.
 */
export function newUuid(): string {
  if (typeof globalThis !== "undefined" && globalThis.crypto?.randomUUID) {
    return globalThis.crypto.randomUUID();
  }

  // RFC 4122 version-4 fallback.
  return "xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g, (c) => {
    const r = Math.floor(Math.random() * 16);
    const v = c === "x" ? r : (r & 0x3) | 0x8;
    return v.toString(16);
  });
}
